name: tensorflow
dependencies:
- openssl=1.0.2h=1
- pip=8.1.2=py35_0
- python=3.5.1=0
- readline=6.2=2
- setuptools=23.0.0=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.0.5=1
- zlib=1.2.8=3
- pip:
  - boto==2.43.0
  - bz2file==0.98
  - decorator==4.0.10
  - gensim==0.13.3
  - numpy==1.11.0
  - praw==3.5.0
  - protobuf==3.0.0b2
  - requests==2.11.1
  - scipy==0.18.1
  - six==1.10.0
  - smart-open==1.3.5
  - tensorflow==0.9.0
  - update-checker==0.11

