-- Database: RedditData
-- Table: Threads


--sqlite RedditData;

create table threads (THREADNO INTEGER PRIMARY KEY, --START FROM 1
					  TOPIC VARCHAR(255) NOT NULL, 
					  TITLE VARCHAR(255) NOT NULL,
					  TIMEPOSTED TIMESTAMP NOT NULL,
					  SENTIMENT INTEGER NOT NULL, --0 FOR PRO-TOPIC, 1 FOR ANTI-TOPIC, 2 FOR IRRELEVANT
					  SUBREDDIT VARCHAR(64) NOT NULL,
					  SELFPOST BOOLEAN NOT NULL,
					  SELFCONTENT BOOLEAN NOT NULL,
					  LINKEDDOMAIN VARCHAR(255) NOT NULL,
					  UPVOTE INTEGER NOT NULL
					  );

create table comments (COMMMENTNO INTEGER PRIMARY KEY, --START FROM 1
					   CONTENT VARCHAR(4096) NOT NULL,
					   THREADNO INTEGER, --WOULD BE 0 IF IT IS A COMMENT OF COMMENT
					   PARENTCOMMENTNO INTEGER, --WOULD BE 0 IF IT IS A COMMENT OF THREAD
					   UPVOTE INTEGER,
					   FOREIGN KEY(THREADNO) REFERENCES threads(THREADNO)
					   );